FORMAT: 1A
HOST: https://app.apiary.io/politicoappapi

# Politicoappapi

Politico enables citizens give their mandate to politicians running for different government offices  while building trust in the process through transparency. 




### List All Parties


        [
            {
                
                "Parties": [
                     {
            "hqAddress": "nairobi",
            "id": 1,
            "logoUrl": "www.mwm.com",
            "party_name": "jubilee"
        },     "hqAddress": "Nakuru",
            "id": 2,
            "logoUrl": "https://kanu.co.ke",
            "party_name": "KANU"
        }, {
            "hqAddress": "Nakuru",
            "id": 3,
            "logoUrl": "https://odm.com",
            "party_name": "PNU"
        }, {
            "hqAddress": "THIKA",
            "id": 4,
            "logoUrl": "https://odm.co.KE",
            "party_name": "PPA"
        }
                ]
            }
        ]

### LIST all Oficces 



        {
             {
        "id": 1,
        "name": "MCA",
        "type": "Legislative"
    },
    {
        "id": 2,
        "name": "MP",
        "type": "Federal"
    },
        }